stages:
  prepare:
    cmd: python prepare.py
    deps:
      - data/raw/credit_data.csv
    outs:
      - data/processed/X_train.csv
      - data/processed/X_test.csv
      - data/processed/y_train.csv
      - data/processed/y_test.csv

  train:
    cmd: python train.py
    deps:
      - data/processed/X_train.csv
      - data/processed/X_test.csv
      - data/processed/y_train.csv
      - data/processed/y_test.csv
    outs:
      - models/model.joblib
    metrics:
      - models/metrics/test_metrics.json:
          cache: false