name: Credit Risk ML Pipeline
on: [push]

jobs:
  train:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    
    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.9'
    
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt
    
    - name: Set up DVC
      uses: iterative/setup-dvc@v1
    
    - name: Pull data from DVC
      run: dvc pull
    
    - name: Prepare data
      run: python src/prepare.py
    
    - name: Train model
      run: python src/train.py
    
    - name: Upload model artifacts
      uses: actions/upload-artifact@v2
      with:
        name: model-files
        path: |
          models/
          data/processed/
